---
title: "R Notebook"
output: html_notebook
---
In order to help inform the planning for provision of cancer treatment services in NHS Borders, we would like to gain better understanding of the incidence of cancer in NHS Borders

```{r}
library(tidyverse)
library(ggplot2)
library(tsibble)
library(fable)
library(lubridate)
library(urca)
library(plotly)
```
```{r}
borders_cancer <- read_csv("clean_data/borders_cancer.csv")
healthboard_cancer <- read_csv("clean_data/healthboard_cancer.csv")
```
###most common cancer types 
```{r}
ten_cancers <- borders_cancer %>% 
  group_by(cancer_site) %>% 
  filter(cancer_site != "All cancer types") %>% 
  summarise(total = sum(incidences_all_ages)) %>% 
  head(10) %>% 
  mutate(cancer_site = recode(cancer_site,
                              "Acute lymphoblastic leukaemia" = "Leukemia",
                              "Acute myeloid leukaemia" = "Leukemia",
                              "All brain and CNS tumours (malignant and non-malignant)" = "Brain",
                              "Basal cell carcinoma of the skin" = "Skin",
                              "Bone and articular cartilage" = "Bone",
                              "Bone and connective tissue" = "Bone",
                              "Carcinoma in situ of the breast" = "Carcinoma",
                              "Carcinoma in situ of the cervix uteri" = "Carcinoma"))

ten_cancers %>% 
  ggplot(aes(x = cancer_site, y = total))+
  geom_col()
```
###distribution of cancer by age
```{r}
borders_cancer %>% 
  summarise(across(starts_with("incidences_age"), sum)) %>% 
  pivot_longer(cols = everything(), 
               names_to = "age_bracket",
               values_to = "incidences_of_cancer") %>%
  mutate(age_bracket = str_remove_all(age_bracket, "[a-z]{10}_[a-z]{3}"),
         age_bracket = str_replace_all(age_bracket, "to", "-"),
         age_bracket = str_replace_all(age_bracket, "_under", "-"),
         age_bracket = str_replace_all(age_bracket, "and_over", "+")) %>% 
  ggplot(aes(x = age_bracket,
             y = incidences_of_cancer))+
  geom_col()

```
```{r}
cancer_types_time <- borders_cancer %>% 
  mutate(year = make_date(year),
         year = year(year)) %>% 
  filter(sex == "All", cancer_site != "All cancer types") %>% 
  select(year, incidences_all_ages, cancer_site) %>% 
  tsibble(index = year, key = c(cancer_site, incidences_all_ages)) %>% 
  group_by(cancer_site) %>% 
  summarise(incidences_all_ages = sum(incidences_all_ages)) 

types <- cancer_types_time %>% 
ggplot(aes(x = year,
           y = incidences_all_ages, colour = cancer_site))+
  geom_line()+
  theme(legend.position = "none")
```



###cancer trend over time
```{r}
borders_cancer_time <- borders_cancer %>% 
  mutate(year = make_date(year),
         year = year(year)) %>% 
  filter(sex == "All", cancer_site == "All cancer types") %>% 
  select(year, incidences_all_ages)

borders_cancer_time <- as_tsibble(borders_cancer_time, index = year)

borders_cancer_time %>% 
  autoplot(incidences_all_ages)
```
#forecast
```{r}


fit <- borders_cancer_time %>% 
  model( #creating fitted model
    mean_model = MEAN(incidences_all_ages),
    arima = ARIMA(incidences_all_ages),
    arima000 = ARIMA(incidences_all_ages ~ pdq(0,0,0)) #non-seasonal fit
  )

forecast <- fit %>% 
  forecast(h = 3) #forecast 3 years in advance 

forecast %>% #plot forecasts
  autoplot(borders_cancer_time)

?ARIMA
```
#finding most accurate model
```{r}
years <- borders_cancer_time %>% #recorded years
  distinct(year) %>% 
  arrange(desc(year))

train <- borders_cancer_time %>% 
  filter_index("1996" ~ "2017")#training on data up to 2017

fit_train <- train %>% 
  model(
    mean_model = MEAN(incidences_all_ages),
    arima = ARIMA(incidences_all_ages),
    arima000 = ARIMA(incidences_all_ages ~ pdq(0,0,0))#create fit
  )

forecast_test <- fit_train %>% 
  fabletools::forecast(h =3) #test forecast

forecast_test %>% 
  autoplot(train, level = NULL)+
  autolayer(filter_index(borders_cancer_time, "2017" ~ .), colour = "black")
#models of similar accuracy, so keep both
```

