---
title: "R Notebook"
output: html_notebook
---
#question 1
```{r}
weather_list <- list(
  "thursday" = list(temperature = 19, rain_chance = 40, wind_speed = 5),
  "friday" = list(temperature = 18, rain_chance = 80, wind_speed = 10),
  "saturday" = list(temperature = 22, rain_chance = 70, wind_speed = 3)
)
```
#question 2
```{r}
weather_list[[1]][[2]]

weather_list[[2]][[3]]

weather_list[[1]][[1]]
```

#question 3 
```{r}
weather_matrix <- matrix(c(20, 19, 22, 22, 20, 20 , 20, 21, 21, 22, 22, 22, 20, 19), nrow = 2, ncol = 7)

weather_matrix
```
#question 4
```{r}
weather_matrix[2, 3]
weather_matrix[2, 1:7]
weather_matrix[ , c(1, 3, 5)]
```

#question 5
```{r}
answer <- function(x) {
  if (is.character(x)) {
    return(paste("The answer is:", x))
  }

  if (is.numeric(x)) {
    if (x < 10) {
      return(x)
    } else {
      return(x / 10)
    }
  }

  return("Invalid input")
}
```


#question 6 
```{r}
is_same_vector <- function(vector_1, vector_2) {
  if (all(vector_1 == vector_2)) {
    return("Exactly the same")
  }

  if (all(sort(vector_1) == sort(vector_2))) {
    return("The same")
  }

  return("Different")
}
```


#question 7 
```{r}
multiplication_table <- matrix(nrow = 12, ncol = 12)

for (outer_factor in 1:12) {
  for (inner_factor in 1:12) {
    multiplication_table[outer_factor, inner_factor] = outer_factor * inner_factor
  }
}
```


