---
title: "R Notebook"
output: html_notebook
---
```{r}
library(rpart)
library(rpart.plot)
library(tidyverse)
library(ggfortify)
library(GGally)

library(tidyverse)
titanic_set <- read_csv('data/titanic_decision_tree_data.csv')

shuffle_index <- sample(1:nrow(titanic_set))

# shuffle the data so class order isn't in order - need this for training/testing split later on 
titanic_set <- titanic_set[shuffle_index, ]
```
###1
```{r}
titanic_clean <- titanic_set %>%
  filter(survived %in% c(0,1)) %>%
    mutate(sex = as.factor(sex), 
           age_status = as.factor(if_else(age <= 16, "child", "adult")),
         class = factor(pclass, levels = c(3,2,1), labels = c("Lower", "Middle", "Upper")), 
           survived_flag = factor(survived, levels = c(0,1), labels = c("No", "Yes")), 
           port_embarkation = as.factor(embarked)) %>%
  select(sex, age_status, class, port_embarkation, sib_sp, parch, survived_flag) %>%
  na.omit()
```

###2
```{r}
ggpairs(titanic_clean, titanic_clean)
```
gender, class ticket seem like good predictors

###3
```{r}
n_data <- nrow(titanic_clean)

test_index <- sample(1:n_data, size = n_data*0.25) #using 0.25 as there's not that many observations

titanic_test <- slice(titanic_clean, test_index)

titanic_train <- slice(titanic_clean, -test_index)
```

```{r}
titanic_test %>% 
  janitor::tabyl(survived_flag)

titanic_train %>% 
  janitor::tabyl(survived_flag)

#relatively balanced, although slightly off in % terms due to size of dataset
```

###4
```{r}
titanic_fit <- rpart(
  formula = survived_flag ~ .,
  data = titanic_train,
  method = "class"
)

rpart.plot(titanic_fit,
           yesno = 2,
           fallen.leaves = TRUE,
           faclen = 6,
           digits = 2)
```

###5
```{r}
rpart.rules(titanic_fit, cover = TRUE)

a male, child, with 3 or more family members on board has a 7% chance of surviving
a male adult has a 17% chance of surviving
a male with less than 3 family members onboard who is a child and no parents has a 25% chance of surviving
a female with more than 1 family member in lower has a 37% chance of survival
a female with no family on board in lower class has a 58% chance of survival
a male child with less than 3 family members and at least 1 parent has a 84% chanec of survival
a female in upper/middle class has a 93% chance of survival
```

###6
```{r}
library(modelr)

titanic_test_pred <- titanic_test %>% 
  add_predictions(titanic_fit, type = "class")

library(yardstick)

conf_mat <- titanic_test_pred %>% 
  conf_mat(truth = survived_flag, estimate = pred)

accuracy <- titanic_test_pred %>% 
  accuracy(truth = survived_flag, estimate = pred)
```
this measure of accuracy means that our prediction has a 0.826 probability of being correct.

###ext
```{r}
library(ranger)
library(caret)

control <- trainControl(
  method = "repeatedcv", 
  number = 5, 
  repeats = 10
)

tune_grid = expand.grid(
  mtry = 1:6,
  splitrule = c("gini", "extratrees"),
  min.node.size = c(1, 3, 5)
)
rf_tune <- train(
  survived_flag ~ ., 
  data = titanic_train, 
  method = "ranger",
  metric = "Kappa",
  num.trees = 1000,
  importance = "impurity",
  tuneGrid = tune_grid, 
  trControl = control
)

plot(rf_tune)
rf_tune
```
```{r}
titanic_classifier <- ranger(survived_flag ~ ., 
                        data = titanic_train, 
                        importance = "impurity", 
                        num.trees = 1000, 
                        mtry = 2, 
                        min.node.size = 5)

importance(titanic_classifier) #sex is the most important classifier

titanic_test_pred <- titanic_test %>% #add prediciton to test accuracy
  mutate(pred = predict(titanic_classifier, data = titanic_test)$predictions)

confusionMatrix(titanic_test_pred$pred, titanic_test_pred$survived_flag) 
#83.15% accuracy (higher than single decision tree)
```

