---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(shiny)
library(ggplot2)
library(CodeClanData)
library(plotly)

```
```{r}
game_sales <- CodeClanData::game_sales
```



```{r}
sales_genre <- game_sales %>% 
  group_by(genre, year_of_release) %>% 
  summarise(sales = round(mean(sales), 2), .groups = "keep") %>% 
  mutate(year_of_release = as.factor(year_of_release)) %>% 
  arrange(year_of_release) %>% 
  filter(year_of_release == "2012") %>% 
  ggplot(aes(x = genre,
             y = sales,
             fill = "coral"))+
  geom_col()+
  coord_flip()+
  theme(panel.grid = element_blank(),
        panel.background = element_blank(),
        legend.position = "none")+
  labs(x = "Genre",
       y = "Sales (£m)")
```
```{r}
ggplotly(sales_genre)
```

```{r}
score_genre <- game_sales %>% 
  group_by(genre, year_of_release) %>% 
  summarise(user_score = round(mean(user_score), 2), .groups = "keep") %>% 
  mutate(year_of_release = as.factor(year_of_release)) %>% 
  arrange(year_of_release) %>% 
  filter(year_of_release == "2012") %>% 
  ggplot(aes(x = genre,
             y = user_score,
             fill = "coral"))+
  geom_col()+
  coord_flip()+
  theme(panel.grid = element_blank(),
        panel.background = element_blank(),
        legend.position = "none")+
  labs(x = "Genre",
       y = "User Score")
```
```{r}
ggplotly(score_genre)
```


```{r}
year_vs_sales <- game_sales %>% 
  group_by(genre, year_of_release) %>% 
  summarise(sales = round(mean(sales), 2), .groups = "keep") %>% 
  filter(genre == "Action") %>% 
ggplot(aes(x = year_of_release,
             y = sales,
             fill = genre))+
  geom_col(show.legend = F)+
  coord_flip()+
  theme(panel.grid = element_blank(),
        panel.background = element_blank())+
  labs(x = "Release Year",
       y = "Sales (£m)")
```
```{r}
ggplotly(year_vs_sales)
```


```{r}
year_vs_score <- game_sales %>% 
  group_by(genre, year_of_release) %>% 
  summarise(user_score = round(mean(user_score), 2), .groups = "keep") %>% 
  filter(genre == "Action") %>% 
  ggplot(aes(x = year_of_release,
             y = user_score,
             fill = genre))+
  geom_col(show.legend = F)+
 coord_flip()+
  theme(panel.grid = element_blank(),
        panel.background = element_blank())+
  labs(x = "Release Year",
       y = "User Score")
```
```{r}
ggplotly(year_vs_score)
```

